version: '3.8'
services:
  crystal-bot:
    container_name: crystal-bot
    restart: unless-stopped
    build:
      context: .
    environment:
      - TOKEN=YOURTOKENHERE
      - PREFIX=.
      - ADMINS=1234
      - SHARDS=1
      - CHANNEL_ID=YOURCHANNELIDHERE
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=crystalbot
