version: '3.8'
services:
  crystal-bot:
    container_name: crystal-bot
    restart: unless-stopped
    build:
      context: .
    environment:
      - TOKEN=YOURTOKENHERE
      - ADMINS=1234
      - SHARDS=1
      - CHANNEL_ID=YOURCHANNELIDHERE
