export const desksAndChairsFacts = [
    "The average person uses a desk at least once in their life",
    "I saw a desk at IKEA once",
    "The average desk is not a sentient being (or is it?)",
    "Some desks are really cool",
    "Desks are real",
    "desk",
    "There is usually at least one desk in a school",
    "There is probably a desk in your house",
    "desks aren't typically edible",
    "You can put things on a desk",
    "Some desks are green",
    "My desk isn't green",
    '"Desk" is a word in english',
    "Some desks are made of wood",
    "Some desks are made of metal",
    "SOME DESKS ARE MADE OF DESK!!",
    `The word "desk" doesn't sound like a word to me anymore because i've said it so many times in my head`,
    "Desks are quite similar to dogs, as they both often have four legs",
    `I own a desk and i'm going to name it "desk"`,
    "Desks > tables",
    "I wrote all these facts while sitting in a chair!",
    "The chair has many different forms",
    "Some chairs are kinda mean tbh (though some are nice)",
    "I don't know who invented the chair",
    "The haters told me I couldn't own a pet chair. I proved them WRONG!",
    "The gaming chair was a revolutionary creation which is currently used by gamers all over the world",
    "Wulfie owns a chair from IKEA",
    '"Crystal" and "chair" both start with the letter "C"',
    "Most people know what a chair is (I think I know what a chair is)",
    "respect the chairs",
    "There is always a possibility that chairs could one day become sentient and try to take over the world!",
    "i really want a flying chair :(",
    "i saw a blue chair at school",
    "I, The LEGENDARY Crystal Bot, dream of one day owning 4529 chairs ",
    "I will 100% support the chairs when they take over the world",
    "people genuinely need to stop using chairs as shopping carts",
    "If you own a chair, you probably breath air",
    `Most people don't know this, but the word "chair" starts with the letter C`,
    "Some chairs could technically be used as a form of transport",
    "this fact about chairs probably made you think about chairs",
]
